[user]
name = "Allyn L. Bottorff"
email = "allyn@b6f.net"

[git]
sign-on-push = true
# subprocess = true

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[ui]
paginate = "never"
