live_config_reload = true

# [colors.bright]
# black = "#4c566a"
# blue = "#81a1c1"
# cyan = "#8fbcbb"
# green = "#a3be8c"
# magenta = "#b48ead"
# red = "#bf616a"
# white = "#eceff4"
# yellow = "#ebcb8b"
#
# [colors.cursor]
# cursor = "#d8dee9"
# text = "#2e3440"
#
# [colors.dim]
# black = "#373e4d"
# blue = "#68809a"
# cyan = "#6d96a5"
# green = "#809575"
# magenta = "#8c738c"
# red = "#94545d"
# white = "#aeb3bb"
# yellow = "#b29e75"
#
# [colors.normal]
# black = "#3b4252"
# blue = "#81a1c1"
# cyan = "#88c0d0"
# green = "#a3be8c"
# magenta = "#b48ead"
# red = "#bf616a"
# white = "#e5e9f0"
# yellow = "#ebcb8b"
#
# [colors.primary]
# background = "#2e3440"
# dim_foreground = "#a5abb6"
# foreground = "#d8dee9"
#
# # [colors.search.footer_bar]
# # background = "#434c5e"
# # foreground = "#d8dee9"
#
# [colors.search.matches]
# background = "#88c0d0"
# foreground = "CellBackground"
#
# [colors.selection]
# background = "#4c566a"
# text = "CellForeground"
#
# [colors.vi_mode_cursor]
# cursor = "#d8dee9"
# text = "#2e3440"


# Colors (Nordic)

[colors.primary]
background = '#242933'
foreground = '#BBBDAF'

[colors.normal]
black = '#191C1D'
red = '#BD6062'
green = '#A3D6A9'
yellow = '#F0DFAF'
blue = '#8FB4D8'
magenta = '#C7A9D9'
cyan = '#B6D7A8'
white = '#BDC5BD'

[colors.bright]
black = '#727C7C'
red = '#D18FAF'
green = '#B7CEB0'
yellow = '#BCBCBC'
blue = '#E0CF9F'
magenta = '#C7A9D9'
cyan = '#BBDA97'
white = '#BDC5BD'

[colors.selection]
text = '#000000'
background = '#F0DFAF'




[cursor.style]
blinking = "On"

[font]
# builtin_box_drawing = true
size = 12

[font.normal]
family = "Berkeley Mono"
# [font.bold]
# family = "Berkeley Mono"
# [font.italic]
# family = "Berkeley Mono"
# [font.bold_italic]
# family = "Berkeley Mono"

[window]
dynamic_padding = true
option_as_alt = "Both"
